const { evaluatePR } = require('./scorer');
const { getPRFiles, postPRComment } = require('./github');

/**
 * Pull Request events handle karne ka main function.
 * Ye event check karta hai, score nikalta hai, aur comment post karta hai.
 */
async function handlePullRequestEvent(octokit, payload) {
  const { action, pull_request, repository } = payload;
  
  // Hum sirf 'opened' aur 'synchronize' events mein interested hain
  if (!['opened', 'synchronize'].includes(action)) {
    return;
  }

  const owner = repository.owner.login;
  const repo = repository.name;
  const pull_number = pull_request.number;

  console.log(`PR #${pull_number} process ho raha hai (${owner}/${repo}), Action: ${action}`);

  // 1. Files ki list mangwao taaki tests check kar sakein
  const files = await getPRFiles(octokit, { owner, repo, pull_number });

  // 2. PR evaluate karo
  const prMetadata = {
    title: pull_request.title,
    body: pull_request.body,
    commits: pull_request.commits,
    additions: pull_request.additions,
    deletions: pull_request.deletions,
    changed_files: pull_request.changed_files
  };

  const report = evaluatePR(prMetadata, files);

  // 3. Comment format karo
  const commentBody = formatReportComment(report);

  // 4. Comment post karo
  await postPRComment(octokit, { owner, repo, pull_number, body: commentBody });
  
  console.log(`PR #${pull_number} ke liye quality report post ho gayi hai`);
}

/**
 * Score aur observations ko GitHub markdown format mein convert karta hai.
 */
function formatReportComment(report) {
  const { score, observations, suggestions } = report;

  let comment = `### GlimOko PR Quality Report\n\n`;
  comment += `**Score: ${score} / 100**\n\n`;

  if (observations.length > 0) {
    comment += `#### Key Observations:\n`;
    observations.forEach(obs => {
      comment += `- ${obs}\n`;
    });
    comment += `\n`;
  }

  if (suggestions.length > 0) {
    comment += `#### Suggestions:\n`;
    suggestions.forEach(sug => {
      comment += `- ${sug}\n`;
    });
    comment += `\n`;
  } else {
    comment += `Bahut badhiya PR! Koi major suggestions nahi hain.\n`;
  }

  comment += `--- \n*Generated by GlimOko*`;

  return comment;
}

module.exports = {
  handlePullRequestEvent
};
